### ISSUE TITLE
Can't push wiki changes

### ISSUE THREAD

**Issue by ilyakrasnov** [jce-il/sw-modeling-2017b#4]
@robi-y I've edited the wiki page with my presentation proposal for ex3 (homebrew). I can't push my changes to the wiki repo and keep getting the error:

`remote: Permission to jce-il/sw-modeling-2017b.wiki.git denied to ilyakrasnov.
fatal: unable to access 'https://github.com/jce-il/sw-modeling-2017b.wiki.git/': The requested URL returned error: 403`

I've updated the [wiki of my fork](https://github.com/ilyakrasnov/sw-modeling-2017b/wiki).

A few questions:
1. Do you have an idea on how to solve it?
2. Would homebrew be ok for the presentation?

Thanks in advance

**Comment by robi-y** [comment]
1. There is a pending invitation for you to join the class team which has the rights for it - look for a mail from github (resent it now)
2. homebrew should be great

**Comment by ilyakrasnov** [comment]
Thanks a lot!
